### ISSUE TITLE
Homebridge crashes on startup trying to get events from iCal

### ISSUE THREAD

**Issue by stephenstarkie** [grover/homebridge-calendar#14]
The log looks like this;

pi@raspberrypi:~ $ homebridge
[12/13/2019, 17:47:26] Loaded config.json with 0 accessories and 1 platforms.
[12/13/2019, 17:47:26] ---
[12/13/2019, 17:47:26] Loaded plugin: homebridge-calendar
[12/13/2019, 17:47:26] Registering platform 'homebridge-calendar.Calendar'
[12/13/2019, 17:47:26] ---
[12/13/2019, 17:47:26] Loading 1 platforms...
[12/13/2019, 17:47:26] [Calendar] Initializing Calendar platform...
[12/13/2019, 17:47:26] [Calendar] CalendarPlatform Plugin Loaded - version 0.4.0
[12/13/2019, 17:47:26] [Calendar] Found calendar in config: "House Calendar"
[12/13/2019, 17:47:26] [Calendar] Pushing calendar sensor 'House Calendar' state 0 - value 0
[12/13/2019, 17:47:26] [Calendar] Pushing calendar sensor 'Heat' state 0 - value 0
[12/13/2019, 17:47:26] [Calendar] Polling calendar House Calendar has started.
[12/13/2019, 17:47:26] [Calendar] Updating calendar House Calendar
[12/13/2019, 17:47:26] [Calendar] Initializing platform accessory 'House Calendar'...
Load homebridge-calendar.Calendar
[12/13/2019, 17:47:26] [homebridge-calendar.Calendar] CalendarPlatform Plugin Loaded - version 0.4.0
Setup Payload:
X-HM://0023ISYWYE733
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                                      
<barcode>
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[12/13/2019, 17:47:26] Homebridge is running on port 51826.
[12/13/2019, 17:47:26] TypeError: Cannot read property 'length' of undefined
    at Component.getAllSubcomponents (/usr/local/lib/node_modules/homebridge-calendar/node_modules/ical.js/build/ical.js:2304:48)
    at new IcalExpander (/usr/local/lib/node_modules/homebridge-calendar/node_modules/ical-expander/index.js:17:34)
    at CalendarPoller._refreshCalendar (/usr/local/lib/node_modules/homebridge-calendar/src/CalendarPoller.js:69:26)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-calendar/src/CalendarPoller.js:54:14)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[12/13/2019, 17:47:26] Got SIGTERM, shutting down Homebridge...

The config looks like this;

{
    "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  "description": "Z-Wave Controller",
  "platforms": [
      {
        "platform": "Calendar",
        "calendars": [
        {
          "name": "House Calendar",
          "url": "webcal://<my public calendar>",
          "pollingInterval": 5,
          "sensors": [
            "Heat"
          ]
        }]
    }]
}

I am using this calendar with Indigo and Cynical Calendars plugin - it usually works - but I am trying to move everything to Homebridge and HomeKit on RPi

**Comment by newmans99** [comment]
I’m not sure if you have this resolved or not, but you may want to validate that the webcal:// URL is publicly available. If it is not, then the calendar will not work.
