### ISSUE TITLE
Plugin crashes homebridge (three users of are affected)

### ISSUE THREAD

**Issue by Kohle81** [grover/homebridge-calendar#37]
Hello @grover ,

since 2 days my homebridge (v.1.3.4, node 14.17.0) crashes when loading this plugin (v 0.4.0).

We are 3 users from smartapfel.de, look at 
https://forum.smartapfel.de/forum/thread/1037-homebridge-calendar-kalender-trigger/?action=firstNew

Here my log from starting homebridge:

May 26 12:34:29 raspberrypi homebridge[32319]: Starting to advertise 'Homebridge-cal B6ED' using ciao backend!
May 26 12:34:29 raspberrypi homebridge[32319]: [26/05/2021, 12:34:29] Homebridge v1.3.4 (Homebridge-cal) is running on port 51873.
May 26 12:34:30 raspberrypi homebridge[32319]: [26/05/2021, 12:34:30]     at new ParserError (/usr/local/lib/node_modules/homebridge-calendar/node_modules/ical.js/build/ical.js:1702:13)
May 26 12:34:30 raspberrypi homebridge[32319]:     at Function.ICAL.parse.parser._handleContentLine (/usr/local/lib/node_modules/homebridge-calendar/node_modules/ical.js/build/ical.js:1890:13)
May 26 12:34:30 raspberrypi homebridge[32319]:     at /usr/local/lib/node_modules/homebridge-calendar/node_modules/ical.js/build/ical.js:1732:14
May 26 12:34:30 raspberrypi homebridge[32319]:     at Function.ICAL.parse.parser._eachLine (/usr/local/lib/node_modules/homebridge-calendar/node_modules/ical.js/build/ical.js:2191:11)
May 26 12:34:30 raspberrypi homebridge[32319]:     at Object.parser [as parse] (/usr/local/lib/node_modules/homebridge-calendar/node_modules/ical.js/build/ical.js:1731:12)
May 26 12:34:30 raspberrypi homebridge[32319]:     at new IcalExpander (/usr/local/lib/node_modules/homebridge-calendar/node_modules/ical-expander/index.js:15:26)
May 26 12:34:30 raspberrypi homebridge[32319]:     at CalendarPoller._refreshCalendar (/usr/local/lib/node_modules/homebridge-calendar/src/CalendarPoller.js:69:26)
May 26 12:34:30 raspberrypi homebridge[32319]:     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-calendar/src/CalendarPoller.js:54:14)
May 26 12:34:30 raspberrypi homebridge[32319]:     at IncomingMessage.emit (events.js:388:22)
May 26 12:34:30 raspberrypi homebridge[32319]:     at endReadableNT (internal/streams/readable.js:1336:12)
May 26 12:34:30 raspberrypi homebridge[32319]: [26/05/2021, 12:34:30] Got SIGTERM, shutting down Homebridge...
May 26 12:34:35 raspberrypi systemd[1]: homebridge-cal.service: Main process exited, code=exited, status=143/n/a
May 26 12:34:35 raspberrypi systemd[1]: homebridge-cal.service: Failed with result 'exit-code'.
^C

I hope you could help.

Greetz Kohle

**Comment by Kohle81** [comment]
Problem is solved. Apple has changed the calendar link.
