### ISSUE TITLE
Plugin error on startup - kills Homebridge

### ISSUE THREAD

**Issue by rakgupta** [grover/homebridge-calendar#38]
Hi - I just installed this plug-in and I am getting this error in the HB logs:

`[6/8/2021, 10:48:34 AM]     at new ParserError (/usr/local/lib/node_modules/homebridge-calendar/node_modules/ical.js/build/ical.js:1641:13)
    at Function.ICAL.parse.parser._handleContentLine (/usr/local/lib/node_modules/homebridge-calendar/node_modules/ical.js/build/ical.js:1829:13)
    at /usr/local/lib/node_modules/homebridge-calendar/node_modules/ical.js/build/ical.js:1671:14
    at Function.ICAL.parse.parser._eachLine (/usr/local/lib/node_modules/homebridge-calendar/node_modules/ical.js/build/ical.js:2130:11)
    at Object.parser [as parse] (/usr/local/lib/node_modules/homebridge-calendar/node_modules/ical.js/build/ical.js:1670:12)
    at new IcalExpander (/usr/local/lib/node_modules/homebridge-calendar/node_modules/ical-expander/index.js:15:26)
    at CalendarPoller._refreshCalendar (/usr/local/lib/node_modules/homebridge-calendar/src/CalendarPoller.js:69:26)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-calendar/src/CalendarPoller.js:54:14)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)`

Install Info is:
`OS | macOS Catalina
Node.js | v14.15.5
npm | v7.5.4`

Plug-in config:
`{
    "platform": "Calendar",
    "calendars": [
        {
            "name": "Cal 1",
            "url": "**url copied from Google calendar sharing link**",
            "pollingInterval": 5,
            "offset": "-8h",
            "sensors": [
                "Sensor 1",
                "Sensor 2"
            ]
        }
    ]
}`

Any help would be appreciated. Thanks!

**Comment by rakgupta** [comment]
My apologies - I was using the wrong link. The correct link for Google is the "Secret address in iCal format". Hope this helps someone....
