### ISSUE TITLE
Newb setup question

### ISSUE THREAD

**Issue by tknospdr** [grover/homebridge-calendar#57]
I just installed HomeBridge in order to use this package.
I'm not really understanding how to fire off events with this plugin.
What I'd like to ideally do, is to enable a scene on a specific calendar day and then disable it on another specific day and repeat those days every year.
If I can't do this I'd just like to set a scene for a specific span of days for certain hours that also repeat every year.

Can I accomplish either of those with this plugin?

**Comment by tknospdr** [comment]
I added the sample lines from the example on the install page and now Homebridge is restarting over and over.

`TypeError: Cannot read properties of undefined (reading 'forEach')
    at CalendarPlatform.accessories (/usr/local/lib/node_modules/homebridge-calendar/src/index.js:39:15)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:534:24
    at new Promise (<anonymous>)
    at BridgeService.loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:528:12)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:479:42
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:401:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:176:29)
[2/23/2023, 1:53:16 PM] Got SIGTERM, shutting down Homebridge...
[2/23/2023, 1:53:16 PM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/usr/local/lib/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/usr/local/lib/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/usr/local/lib/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:527:28)
    at process.emit (/usr/local/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)`
