### ISSUE TITLE
Homebridge 2.0 Support

### ISSUE THREAD

**Issue by timwegenerDE** [grover/homebridge-calendar#59]
Hey,

Soon Homebridge 2.0 will be released which will have some breaking changes to plugins.
Could you please check if this plugin is impacted?

https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

**Comment by TesterTi** [comment]
I just tested v2.0.0-beta23 and received the following error with this plugin:

/var/lib/homebridge/node_modules/homebridge-calendar/src/CalendarAccessory.js:70
    this._bridgingStateService = new Service.BridgingState()

TypeError: Service.BridgingState is not a constructor
    at CalendarAccessory.getBridgingStateService (/var/lib/homebridge/node_modules/homebridge-calendar/src/CalendarAccessory.js:70:34)
    at CalendarAccessory.createServices (/var/lib/homebridge/node_modules/homebridge-calendar/src/CalendarAccessory.js:52:12)
    at new CalendarAccessory (/var/lib/homebridge/node_modules/homebridge-calendar/src/CalendarAccessory.js:27:27)
    at /var/lib/homebridge/node_modules/homebridge-calendar/src/index.js:48:25
    at Array.forEach (<anonymous>)
    at CalendarPlatform.accessories (/var/lib/homebridge/node_modules/homebridge-calendar/src/index.js:39:15)
    at file:///var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:495:24
    at new Promise (<anonymous>)
    at BridgeService.loadPlatformAccessories (file:///var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:489:12)
    at ChildBridgeFork.startBridge (file:///var/lib/homebridge/node_modules/homebridge/src/childBridgeFork.ts:160:36)


It seems from HomeBridge documentation that BridgingState is depreciated. If I remove any reference to it (in [CalendarAccessory.js](https://github.com/grover/homebridge-calendar/blob/master/src/CalendarAccessory.js)) then the plugin works on v2 but I do not know enough about HomeBridge plugins to know what this may break...
