### ISSUE TITLE
Doubling calendar error

### ISSUE THREAD

**Issue by Shadewing666** [grover/homebridge-calendar#9]
Hi grover,

I'm really liking this plugin, it's really helping out.

I was trying to have the same trigger twice, once with a 0 offset and once with a -15 minute offset but as soon as I duplicate the calendar I get the following error:

```
[5/1/2019, 11:45:58 PM] TypeError: Cannot read property 'property' of undefined
	at Function.ICAL.parse.parser._handleContentLine (/homebridge/node_modules/ical.js/build/ical.js:1900:33)
	at /homebridge/node_modules/ical.js/build/ical.js:1732:14
	at Function.ICAL.parse.parser._eachLine (/homebridge/node_modules/ical.js/build/ical.js:2191:11)
	at Object.parser [as parse] (/homebridge/node_modules/ical.js/build/ical.js:1731:12)
	at new IcalExpander (/homebridge/node_modules/ical-expander/index.js:15:26)
	at CalendarPoller._refreshCalendar (/homebridge/node_modules/homebridge-calendar/src/CalendarPoller.js:69:26)
	at IncomingMessage.resp.on (/homebridge/node_modules/homebridge-calendar/src/CalendarPoller.js:54:14)
	at IncomingMessage.emit (events.js:194:15)
	at endReadableNT (_stream_readable.js:1125:12)
	at process._tickCallback (internal/process/next_tick.js:63:19)
[5/1/2019, 11:45:58 PM] Got SIGTERM, shutting down Homebridge...
```
I tried duping the calendar within the platform and duping the platform in the config and I get the same error.

Any ideas?

Thanks,
Edward

**Comment by Shadewing666** [comment]
Cleaning up my created issues. No movement on this and I no-longer use HB
